# Generated by Django 3.1 on 2021-11-06 03:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitemanage', '0003_auto_20211106_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='top_subtitle',
            field=ckeditor.fields.RichTextField(verbose_name='TOPページサブタイトル'),
        ),
    ]
